watch_for:
  - person
  - dog
  - chair
  - phone
  - hand
  - headphone
  - sweets
  - badge
  - backpack
  - handbag
  - cell phone
  - bottle
  - laptop

ignore:
  - chair
  - couch
  - bed

rules:
  require_person: true
  min_confidence: 0.4